config = {
    # need to use refseq since we need to match the transcript IDs in the processed reactivity data
    'genome_annotation': 'ucsc_refseq.2017-06-25',

    # dataset
    # generated by https://github.com/PSI-Lab/alice-sandbox/tree/258b57264f8987fd146f8e7936c7a4e8892cd32b/rna_ss/data_processing/combine_data
    'gtrack': 'data/reactivity_combined.gtrack',
    'all_inervals': 'data/intervals_combined.txt',

    # chromosome for different folds
    'chrom_folds': [['chr1', 'chr10', 'chr15', 'chr20', 'chr22'],
                    ['chr2', 'chr9', 'chr14', 'chr19', 'chr21'],
                    ['chr3', 'chr8', 'chr11', 'chr17'],
                    ['chr4', 'chr7', 'chr12', 'chr18'],
                    ['chr5', 'chr6', 'chr13', 'chr16']],


    # model
    'n_filters': 32,  # n filter in first layer
    'residual_conv': [
        {'num_filter': 32, 'filter_width': 11, 'dilation': 1},
        {'num_filter': 32, 'filter_width': 11, 'dilation': 1},
        {'num_filter': 32, 'filter_width': 11, 'dilation': 1},
        {'num_filter': 32, 'filter_width': 11, 'dilation': 1},
        {'num_filter': 32, 'filter_width': 11, 'dilation': 4},
        {'num_filter': 32, 'filter_width': 11, 'dilation': 4},
        {'num_filter': 32, 'filter_width': 11, 'dilation': 4},
        {'num_filter': 32, 'filter_width': 11, 'dilation': 4},
        {'num_filter': 32, 'filter_width': 21, 'dilation': 10},
        {'num_filter': 32, 'filter_width': 21, 'dilation': 10},
        # {'num_filter': 32, 'filter_width': 21, 'dilation': 10},
        # {'num_filter': 32, 'filter_width': 21, 'dilation': 10},
        # {'num_filter': 32, 'filter_width': 41, 'dilation': 25},
        # {'num_filter': 32, 'filter_width': 41, 'dilation': 25},
        # {'num_filter': 32, 'filter_width': 41, 'dilation': 25},
        # {'num_filter': 32, 'filter_width': 41, 'dilation': 25},
    ],


    'n_repeat_in_residual_unit': 2,
    'skip_conn_every_n': 4,

    'example_length': 100,
    'batch_size': 10,
    'learning_rate': 0.000001,
    'residual': True,
    'skipconn': True,
    'gated': False,

    'num_epoch': 200,
    'num_batch_for_validation': 10,
    'es_patience': 10,

    # final models
    'model_dir': 'model/',

}
